### ISSUE TITLE
Some parts of mesh are not covered by voxel (312_RigVoxelGeodesic)

### ISSUE THREAD

**Issue by 100599002** [nobuyuki83/delfem2#81]
Hi~Nobuyuki. 
I tried to change the mesh and bones with this example "312_RigVoxelGeodesic". 
The code will always crash in line 278 assert( sumw != 0.0 );
I found that voxel did not completely cover the surface. 
Even if I increase the value of ndiv to 300, the program crashes continue to occur.
How can I fix it? Thank you

Model's voxels:
![1593507430428](https://user-images.githubusercontent.com/10720919/86106180-d5339180-baf2-11ea-966d-6221ef096375.jpg)

Voxels around the leg:
![1593506681718](https://user-images.githubusercontent.com/10720919/86105033-69045e00-baf1-11ea-830c-5f64f8c091bd.jpg)

**Comment by nobuyuki83** [comment]
Sorry for my late reply! I had hectic weeks. 

Thanks very much for trying my code and report the problem. The course of the problem is obvious for me --- I assume all the voxels are connected when I compute geodesic in the voxel. There is a simple remedy; use the voxel morphology operation. In this demo, we have an example to inflate voxel: 
https://github.com/nobuyuki83/delfem2/tree/master/examples_glfwold/130_VoxelMorph
You can use the same inflation function to make the voxel connected.
